version: '2.4'

services:
  satuankerja:
    build:
      context: ./service-golang
    command: "satuankerja"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - satuankerja
    env_file: 
      - .env-golang

  jabatan:
    build:
      context: ./service-golang
    command: "jabatan"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - jabatan
    env_file: 
      - .env-golang

  eventuser:
    build:
      context: ./service-golang
    command: "eventuser"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - eventuser
    env_file: 
      - .env-golang

  jobattendance:
    build:
      context: ./service-golang
    command: "jobAttendance"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - jobattendance
    env_file: 
      - .env-golang

  devicetoken:
    build:
      context: ./service-golang
    command: "deviceToken"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - devicetoken
    env_file: 
      - .env-golang

  notificationworker:
    build:
      context: ./service-golang
    command: "notificationWorker"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - notificationworker
    env_file: 
      - .env-golang

  notificationservice:
    build:
      context: ./service-golang
    command: "notificationService"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - notificationservice
    env_file: 
      - .env-golang

  notificationmessage:
    build:
      context: ./service-golang
    command: "notificationMessage"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - notificationmessage
    env_file: 
      - .env-golang

  dayoff:
    build:
      context: ./service-golang
    command: "dayOff"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - dayoff
    env_file: 
      - .env-golang

  holidaydate:
    build:
      context: ./service-golang
    command: "holidayDate"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - holidaydate
    env_file: 
      - .env-golang

  settings:
    build:
      context: ./service-golang
    command: "settings"
    cpus: 0.5
    mem_limit: 100m
    memswap_limit: 150m
    restart: always
    networks:
      - settings
    env_file: 
      - .env-golang

networks:
  satuankerja:
    external:
      name: gateway

  jabatan:
    external:
      name: gateway

  eventuser:
    external:
      name: gateway
  
  jobattendance:
    external:
      name: gateway

  devicetoken:
    external:
      name: gateway

  notificationworker:
      external:
        name: gateway

  notificationservice:
      external:
        name: gateway
  
  notificationmessage:
      external:
        name: gateway

  dayoff:
      external:
        name: gateway

  holidaydate:
      external:
        name: gateway

  settings:
      external:
        name: gateway
