version: '2.4'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - BADGER_EPHEMERAL=false
      - SPAN_STORAGE_TYPE=badger
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - QUERY_BASE_PATH=/jaeger 
      - BADGER_SPAN_STORE_TTL=5m
    networks:
      - jaeger

networks:
  jaeger:
    external:
      name: gateway

