version: '2.4'

services:
  apigateway:
    build:
      context: ./service-nodejs
    command: npm start
    cpus: 0.5
    mem_limit: 300m
    memswap_limit: 150m
    restart: always
    volumes:
      - ./service-nodejs/apiGateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - apigateway
    env_file: 
      - .env-nodejs

  logbook:
    build:
      context: ./service-nodejs
    command: npm start
    cpus: 0.5
    mem_limit: 512m
    memswap_limit: 150m
    restart: always
    volumes:
      - ./service-nodejs/apiLogbook:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - logbook
    env_file: 
      - .env-nodejs

  project:
    build:
      context: ./service-nodejs
    command: npm start
    cpus: 0.5
    mem_limit: 150m
    memswap_limit: 50m
    restart: always
    volumes:
      - ./service-nodejs/apiProject:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - project
    env_file: 
      - .env-nodejs

  attendance:
    build:
      context: ./service-nodejs
    command: npm start
    cpus: 0.5
    mem_limit: 250m
    memswap_limit: 150m
    restart: always
    volumes:
      - ./service-nodejs/apiAttendance:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - attendance
    env_file: 
      - .env-nodejs

  exportpdf:
    build:
      context: ./service-nodejs
    command: npm start
    cpus: 0.75
    mem_limit: 512m
    memswap_limit: 150m
    restart: always
    volumes:
      - ./service-nodejs/apiExportPDF:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - exportpdf
    env_file: 
      - .env-nodejs

networks:
  apigateway:
    external:
      name: gateway

  logbook:
    external:
      name: gateway

  project:
    external:
      name: gateway

  attendance:
    external:
      name: gateway

  exportpdf:
    external:
      name: gateway