# Core
db:
  redis:
    host: ${REDIS_HOST:-redis}
    port: ${REDIS_PORT:-6379}
    emulate: true
    name: mymaster
    namespace: EG

plugins:
  express-gateway-plugin-jaeger:
    package: './plugin/jaeger.js'
    jaegerParams:
      serviceName: 'api-gateway'
      collectorEndpoint: ${JAEGER_COLLECTTOR_END_POINT}

  keycloak-connect:
    package: './plugin/keycloack.js'
    kcConfigParams:
      realm: ${KEYCLOAK_REALM_NAME}
      authServerUrl: ${KEYCLOAK_URL}

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

session:
  # storeProvider: connect-redis
  storeOptions:
    host: ${REDIS_HOST:-redis}
    port: ${REDIS_PORT:-6379}
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
